### ISSUE TITLE
when run python evaluate.py,error as follows

### ISSUE THREAD

**Issue by liujun0621** [CristianoPatricio/coherent-cbe-skin#2]
Traceback (most recent call last):
  File "/root/ccnn/coherent-cbe-skin-main/evaluate.py", line 173, in <module>
    model = model_builder.load_ccbm_model(model=model_name,
  File "/root/ccnn/coherent-cbe-skin-main/modules/model_builder.py", line 1053, in load_ccbm_model
    loaded_model = load_ccbm_densenet201(model_params=params,
  File "/root/ccnn/coherent-cbe-skin-main/modules/model_builder.py", line 870, in load_ccbm_densenet201
    checkpoint = torch.load(saved_model_dir_path)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'saved_models/densenet201/model_PH2_DeepLabV3_FT_concept_loss_relu_tanh_0.6_densenet201_best.pth'

could you share your model_PH2_DeepLabV3_FT_concept_loss_relu_tanh_0.6_densenet201_best.pth?

**Comment by CristianoPatricio** [comment]
Hi @liujun0621,

Please, send me an e-mail (cristiano.patricio@ubi.pt) so that I could share with you the .pth files.
