### ISSUE TITLE
when I train,OpenCV error

### ISSUE THREAD

**Issue by liujun0621** [CristianoPatricio/coherent-cbe-skin#3]
first config:
# Dataset Information
DATASET = "PH2_DeepLabV3_FT"
IMAGES_DIR = "/home/user/Datasets/PH2Dataset/PH2_Segmented_Images_DLab_Trained_on_HAM10000"
MASKS_DIR = "/home/user/Datasets/PH2Dataset/PH2_Masks_HAM10000"

second download：
PH2: https://www.fc.up.pt/addi/ph2%20database.html

 when run train, as follows:
Traceback (most recent call last):
  File "/root/ccnn/coherent-cbe-skin-main/model_training.py", line 292, in <module>
    _, model_1 = engine.train(model=model,
  File "/root/ccnn/coherent-cbe-skin-main/modules/engine.py", line 262, in train
    train_loss, s_loss, c_loss, u_loss, concept_loss, train_acc = train_step(model=model,
  File "/root/ccnn/coherent-cbe-skin-main/modules/engine.py", line 72, in train_step
    for batch, data in enumerate(dataloader):
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/ccnn/coherent-cbe-skin-main/dataset.py", line 57, in __getitem__
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor
what problem could i take? what should i do next?

**Comment by liujun0621** [comment]
what is the relationship between data  when we have downloaded from websit :
https://www.fc.up.pt/addi/ph2%20database.html and 
"IMAGES_DIR = "/home/user/Datasets/PH2Dataset/PH2_Segmented_Images_DLab_Trained_on_HAM10000"
MASKS_DIR = "/home/user/Datasets/PH2Dataset/PH2_Masks_HAM10000""

**Comment by CristianoPatricio** [comment]
Hi @liujun0621,

Thanks for your interest in our work.
You need the masks from PH2 dataset. Please, send me an e-mail (cristiano.patricio@ubi.pt) so that I could share with you the masks and the preprocessed data.

**Comment by liujun0621** [comment]
ｔｈａｎｓｋｓ　ｖｅｒｙ　ｍｕｃｈ
ｗｈｅｎ　ｉ　ｕｓｅ　ｔｒａｉｎｉｎｇ　ｒｅｓｕｌｔ　ｗｈｉｃｈ　ｉ　ｔｒａｉｎｅｄ
ｔｈｅ　ｅｖａ　ａｓ　ｆｏｌｌｏｗｓ：
--------------------------------------------------------
                  2024-09-23 16:33:20
--------------------------------------------------------

///////////   Dataset & Model Information   ////////////

Dataset: PH2_DeepLabV3_FT_concept_loss_relu_tanh_0.6
Image Size: (765, 574)
Image Type: Segmented (DeepLabV3 FT on HAM10000)
Model: densenet201
Learning Rate: 0.001
No. Epochs: 100
Batch-Size: 16
///////////  Evaluation Report - Concepts  ////////////

Exact Match Ratio: 0.0000
Hamming loss: 0.5050
Recall: 0.4571
Precision: 0.9480
F1 Measure: 0.6114

F1 Measure per Concept: [0.09 0.66 0.07 0.71 0.45 0.23 0.66 0.07]
L2 distance: 10.04987562112089

/////////// Classification Report - Classes ////////////

Accuracy: 80.0000%

              precision    recall  f1-score   support

       Nevus       0.80      1.00      0.89        20
    Melanoma       0.00      0.00      0.00         5

    accuracy                           0.80        25
   macro avg       0.40      0.50      0.44        25
weighted avg       0.64      0.80      0.71        25

Confusion Matrix:
[[20  0]
 [ 5  0]]
AUC: 0.5
Sensitivity: 0.0
Specificity: 1.0
BACC: 0.5

**Comment by liujun0621** [comment]
ｗｈｅｎ　ｉ　ｔｒａｉｎｅｄ，ｔｈｅｒｅ　ａｒｅ　ｎｏ　ｓａｖｅｍｏｄｅｌ　ｒｅｓｕｌｔ．
